name: Sync Fork

on:
  schedule:
    # Runs every day at midnight UTC (adjust as needed)
    - cron: '0 0 * * *'

jobs:
  sync_fork:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your fork's main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Configure Git with a user name and email
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 3: Add the upstream repository
      - name: Add upstream remote
        run: git remote add upstream https://github.com/Vendicated/Vencord.git

      # Step 4: Fetch upstream changes
      - name: Fetch upstream
        run: git fetch upstream

      # Step 5: Merge upstream/main into your fork's main branch
      - name: Merge upstream changes
        run: |
          git merge upstream/main --allow-unrelated-histories --no-ff -m "Sync upstream changes"

      # Step 6: Push the merged changes back to your fork
      - name: Push changes to fork
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
