name: Sync to Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
      # Step 1: Checkout your fork's main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Run the sync action
      - name: Pull upstream changes
        id: sync
        uses: bdougie/Fork-Sync-With-Upstream-action@fork
        with:
          upstream_repository: Vendicated/Vencord  # Update to your upstream repo
          upstream_branch: main
          target_branch: main                     # Optional: defaults to checked-out branch
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Optional: for authenticated access
