name: Sync Fork
on:
  schedule:
    # This will run every day at midnight (adjust the cron expression as needed)
    - cron: '0 0 * * *'
jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout your fork's main branch
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        ref: main
    # Step 2: Pull changes from the upstream repository
    - name: Pull upstream changes
      run: |
        git remote add upstream https://github.com/Vendicated/Vencord.git
        git fetch upstream
        git merge upstream/main --allow-unrelated-histories
    # Step 3: Push changes back to your fork
    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
